version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: testExerciseWallet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testExerciseWallet
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
